In [1]:
from typing import Tuple
import pandas as pd
from tqdm.notebook import tqdm
from pymatgen.core import Structure
from wyckoff_transformer.evaluation.generated_dataset import GeneratedDataset, load_all_from_config
from wyckoff_transformer.evaluation.novelty import NoveltyFilter, filter_by_unique_structure

In [2]:
datasets = {
    "WyckoffTransformer-raw": ("WyckoffTransformer",),
    "WyFormer-harmonic-raw": ("WyckoffTransformer-harmonic",),
    "WyFormer-letters": ("WyckoffTransformer-letters",),
    "WyFormer-letters-DiffCSP++": ("WyckoffTransformer-letters", "DiffCSP++", "CHGNet_fix"),
    "SymmCD": ("SymmCD", "CHGNet_fix"),
    "SymmCD-raw": ("SymmCD",),
    "WyFormer": ("WyckoffTransformer", "CrySPR", "CHGNet_fix_release"),
    "WyFormer-harmonic-DiffCSP++": ("WyckoffTransformer-harmonic", "DiffCSP++", "CHGNet_fix"),
    "WyForDiffCSP++": ("WyckoffTransformer", "DiffCSP++", "CHGNet_fix"),
    "WyLLM-naive-DiffCSP++": ("WyckoffLLM-naive", "DiffCSP++", "CHGNet_fix"),
    "WyLLM-vanilla-DiffCSP++": ("WyckoffLLM-vanilla", "DiffCSP++"),
    "WyLLM-site-symmetry-DiffCSP++": ("WyckoffLLM-site-symmetry", "DiffCSP++"),
    #"WyckoffTransformer-free": ("WyckoffTransformer", "CrySPR", "CHGNet_free"),
    "CrystalFormer": ("CrystalFormer", "CHGNet_fix_release"),
    #"DiffCSP++ raw": ("DiffCSP++",),
    "DiffCSP++": ("DiffCSP++", "CHGNet_fix_release"),
    "DiffCSP": ("DiffCSP", "CHGNet_fix"),
    "FlowMM": ("FlowMM", "CHGNet_fix"),
    "MiAD": ("MiAD", "CHGNet_free"),
    "MatterGen": ("MatterGen", "MatterGen_10k", "CHGNet_fix")
    #"MP-20 train": ("split", "train"),
    #"MP-20 test": ("split", "test"),
}
raw_datasets = {
    "SymmCD": ("SymmCD",),
    "WyFormer": ("WyckoffTransformer", "CrySPR", "CHGNet_fix_release"),
    "WyFormerDiffCSP++": ("WyckoffTransformer", "DiffCSP++"),
    "WyFormer-harmonic-DiffCSP++": ("WyckoffTransformer-harmonic", "DiffCSP++"),
    "WyFormer-letters-DiffCSP++": ("WyckoffTransformer-letters", "DiffCSP++"),
    "WyLLM-DiffCSP++": ("WyckoffLLM-naive", "DiffCSP++"),
    "CrystalFormer": ("CrystalFormer",),
    "DiffCSP++": ("DiffCSP++",),
    "DiffCSP": ("DiffCSP",),
    "FlowMM": ("FlowMM",),
    "MatterGen": ("MatterGen", "MatterGen_10k")
}

In [3]:
all_datasets = load_all_from_config(
    datasets=list(datasets.values()) + list(raw_datasets.values()) + \
        [("split", "train"), ("split", "val"), ("split", "test"), ("WyckoffTransformer", "CrySPR", "CHGNet_fix")],
    dataset_name="mp_20")

In [4]:
wycryst_transformations = ('WyCryst', 'CrySPR', 'CHGNet_fix')
datasets["WyCryst"] = wycryst_transformations
raw_datasets["WyCryst"] = wycryst_transformations
all_datasets[wycryst_transformations] = GeneratedDataset.from_cache(wycryst_transformations, "mp_20_biternary")

In [5]:
novelty_reference = pd.concat([
    all_datasets[('split', 'train')].data,
    all_datasets[('split', 'val')].data], axis=0, verify_integrity=True)
novelty_filter = NoveltyFilter(novelty_reference)

In [7]:
from wyckoff_transformer.evaluation.statistical_evaluator import StatisticalEvaluator
test_evaluator = StatisticalEvaluator(all_datasets[('split', 'test')].data)

In [8]:
from wyckoff_transformer.evaluation.novelty import record_to_anonymous_fingerprint
train_w_template_set = frozenset(novelty_reference.apply(record_to_anonymous_fingerprint, axis=1))

In [9]:
def is_sg_preserved(relaxed_sg, transformations: Tuple[str]) -> pd.Series:
    source_sg = all_datasets[(transformations[0],)].data.spacegroup_number
    return relaxed_sg == source_sg.reindex_like(relaxed_sg)

In [10]:
mp_20 = pd.concat([
    all_datasets[('split', 'train')].data,
    all_datasets[('split', 'test')].data,
    all_datasets[('split', 'val')].data], axis=0, verify_integrity=True)
(mp_20.spacegroup_number == 1).mean()
mp_20.smact_validity.mean()

0.9057020937893829

In [11]:
from collections import Counter
from operator import itemgetter
from itertools import chain
element_counts = Counter(chain(*mp_20.elements))

In [12]:
represented_elements=frozenset(map(itemgetter(0), element_counts.most_common(30)))

In [13]:
def check_represented_composition(structure: Structure) -> bool:
    for element in structure.composition:
        if element not in represented_elements:
            return False
    return True

In [14]:
def check_double_represented_composition(structure: Structure) -> bool:
    found_first_exotic = False
    for element in structure.composition:
        if element not in represented_elements:
            if found_first_exotic:
                return False
            found_first_exotic = True
    return True

In [15]:
top_10_groups = frozenset(mp_20.spacegroup_number.value_counts().iloc[:10].index)
n_elements_dist = {}

In [16]:
from scipy.stats import ttest_ind

Validity
1. Vanilla; Valid records: 2866 / 9648 = 29.71%
2. Naive; Valid records: 9492 / 9804 = 96.82%
3. Site Symmetry; Valid records: 8955 / 9709 = 92.23%

Formal validity:
1. WyFomer: 0.9772; [WanDB](https://wandb.ai/symmetry-advantage/WyckoffTransformer/runs/yj1cme83/logs?nw=nwuserkazeev)
2. SymmCD: 0.9580

In [18]:
table = pd.DataFrame(
    index=datasets.keys(), columns=[
        "Novelty (%)",
        "Represented composition",
        "Structural", "Compositional", 
        "Recall", "Precision",
        r"$\rho$", "$E$", "# Elements",
        "S.U.N. (%)",
        "R.S.U.N. (%)",
        "~R.S.U.N. (%)",
        "Top-10 S.U.N. (%)",
        "Novel Uniques Templates (#)",
        "Novel Template (%)", 
        "P1 (%)",
        "Space Group", "S.S.U.N. (%)"])
table.index.name = "Method"
E_hull_threshold = 0.08
precision_etc_sample_size = 1000
best_p1 = (novelty_filter.get_novel(filter_by_unique_structure(
    all_datasets[("WyckoffTransformer", "DiffCSP++", "CHGNet_fix")].data)).group == 1).astype(float)
for name, transformations in tqdm([("train", ("split", "train"))]+list(datasets.items())):
    data = all_datasets[transformations].data.copy()
    if len(data) > precision_etc_sample_size:
        data = data.sample(precision_etc_sample_size, random_state=42)
    unique = filter_by_unique_structure(data)
    print(f"{name} unique: {len(unique)} / {len(data)} = {len(unique) / len(data) :.3%}")
    if transformations == ("split", "train"):
        novel = unique
    else:
        novel = novelty_filter.get_novel(unique)
    table.loc[name, "Novelty (%)"] = 100 * len(novel) / len(unique)
    if "structural_validity" in novel.columns:
        table.loc[name, "Structural"] = 100 * novel.structural_validity.mean()
        table.loc[name, "Compositional"] = 100 * novel.smact_validity.mean()
    if "cdvae_crystal" in novel.columns:
        table.loc[name, "Represented composition"] = novel.structure.apply(check_represented_composition).mean()
        cov_metrics = test_evaluator.get_coverage(novel.cdvae_crystal)    
        table.loc[name, "Recall"] = 100 * cov_metrics["cov_recall"]
        table.loc[name, "Precision"] = 100 * cov_metrics["cov_precision"]
        novel = novel[novel.structural_validity]
        all_templates = novel.apply(record_to_anonymous_fingerprint, axis=1)
        novel_template = ~all_templates.isin(train_w_template_set)
        table.loc[name, "Novel Template (%)"] = 100 * novel_template.mean()
        table.loc[name, "Novel Uniques Templates (#)"] = all_templates[novel_template].nunique() 
        table.loc[name, r"$\rho$"] = test_evaluator.get_density_emd(novel)
        table.loc[name, "$E$"] = test_evaluator.get_cdvae_e_emd(novel)
        table.loc[name, "# Elements"] = test_evaluator.get_num_elements_emd(novel)
        n_elements_dist[name] = novel.elements.apply(lambda e: len(frozenset(e))).value_counts() / len(novel)
    p1 = (novel.group == 1).astype(float)
    table.loc[name, "P1 (%)"] = 100 * p1.mean()
    table.loc[name, "P1 p_value"] = ttest_ind(p1, best_p1).pvalue
    # table.loc[name, "# DoF"] = test_evaluator.get_dof_emd(novel)
    table.loc[name, "Space Group"] = test_evaluator.get_sg_chi2(novel)
    #try:
    #    table.loc[name, "SG preserved (%)"] = 100 * is_sg_preserved(novel.spacegroup_number, transformations).mean()
    #except KeyError:
    #    pass
    #table.loc[name, "Elements"] = test_evaluator.get_elements_chi2(novel)
    if "corrected_chgnet_ehull" in novel.columns:
        # S.U.N. is measured with respect to the initial structures
        has_ehull = data.corrected_chgnet_ehull.notna()
        data_is_represented = data.structure.apply(check_represented_composition)
        is_sun = (novel.corrected_chgnet_ehull <= E_hull_threshold) # & (novel.elements.apply(lambda x: len(frozenset(x))) >= 2)
        table.loc[name, "S.U.N. (%)"] = 100 * is_sun.sum() / has_ehull.sum()
        is_represented_novel = novel.structure.apply(check_represented_composition)
        table.loc[name, "R.S.U.N. (%)"] = 100 * (is_sun & is_represented_novel).sum() / (has_ehull & data_is_represented).sum()
        table.loc[name, "~R.S.U.N. (%)"] = 100 * (is_sun & ~is_represented_novel).sum() / (has_ehull & ~data_is_represented).sum()
        table.loc[name, "S.S.U.N. (%)"] = 100 * (is_sun & (novel.group != 1)).sum() / has_ehull.sum()
        has_ehull_top_10 = data[data.spacegroup_number.isin(top_10_groups)].corrected_chgnet_ehull.notna().sum()
        table.loc[name, "Top-10 S.U.N. (%)"] = 100 * is_sun[novel.spacegroup_number.isin(top_10_groups)].sum() / has_ehull_top_10
    #if transformations == ("split", "train"):
        # Train forms the baseline of the hull
      #  test_dataset = all_datasets[("split", "test")].data
      #  test_with_ehull = test_dataset[test_dataset.corrected_chgnet_ehull.notna()]
      #  test_unique = filter_by_unique_structure(test_with_ehull)
      #  test_novel = novelty_filter.get_novel(test_unique)
      #  table.loc[name, "S.U.N. (%)"] = 100 * (test_novel.corrected_chgnet_ehull <= E_hull_threshold).sum() / len(test_with_ehull)
n_elements_dist["MP-20"] = mp_20.elements.apply(lambda e: len(frozenset(e))).value_counts() / len(mp_20)
table

  0%|          | 0/20 [00:00<?, ?it/s]

train unique: 1000 / 1000 = 100.000%
WyckoffTransformer-raw unique: 999 / 1000 = 99.900%
WyFormer-harmonic-raw unique: 999 / 1000 = 99.900%
WyFormer-letters unique: 995 / 1000 = 99.500%
WyFormer-letters-DiffCSP++ unique: 958 / 959 = 99.896%
SymmCD unique: 998 / 1000 = 99.800%
SymmCD-raw unique: 998 / 1000 = 99.800%
WyFormer unique: 1000 / 1000 = 100.000%
WyFormer-harmonic-DiffCSP++ unique: 983 / 983 = 100.000%
WyForDiffCSP++ unique: 1000 / 1000 = 100.000%
WyLLM-naive-DiffCSP++ unique: 979 / 981 = 99.796%
WyLLM-vanilla-DiffCSP++ unique: 568 / 1000 = 56.800%
WyLLM-site-symmetry-DiffCSP++ unique: 998 / 999 = 99.900%
CrystalFormer unique: 988 / 992 = 99.597%
DiffCSP++ unique: 999 / 1000 = 99.900%
DiffCSP unique: 996 / 1000 = 99.600%
FlowMM unique: 994 / 997 = 99.699%
MiAD unique: 997 / 1000 = 99.700%
MatterGen unique: 997 / 1000 = 99.700%
WyCryst unique: 994 / 994 = 100.000%

,Novelty (%),Represented composition,Structural,Compositional,Recall,Precision,$\rho$,$E$,# Elements,S.U.N. (%),R.S.U.N. (%),~R.S.U.N. (%),Top-10 S.U.N. (%),Novel Uniques Templates (#),Novel Template (%),P1 (%),Space Group,S.S.U.N. (%),P1 p_value
Method,,,,,,,,,,,,,,,,,,,
WyckoffTransformer-raw,91.791792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.181025,0.204613,NaN,2.299249e-01
WyFormer-harmonic-raw,92.492492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.380952,0.174001,NaN,1.379838e-01
WyFormer-letters,90.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5625,0.207784,NaN,8.191949e-01
WyFormer-letters-DiffCSP++,89.979123,0.207657,99.535963,82.830626,98.143852,96.937873,0.432466,0.03743,0.114151,30.96976,29.166667,31.421121,33.26572,224,32.983683,1.165501,0.219905,30.448384,6.221206e-01
SymmCD,88.376754,0.190476,95.804989,84.693878,99.546485,94.461641,0.611053,0.105891,0.527516,33.7,32.786885,33.904529,37.837838,133,23.431953,2.366864,0.240129,32.8,1.501711e-01
SymmCD-raw,89.378758,0.211883,100.0,84.304933,99.663677,94.141057,0.113228,0.208906,0.447636,NaN,NaN,NaN,NaN,123,20.179372,1.793722,0.257048,NaN,5.421805e-01
WyFormer,91.3,0.198248,99.561884,80.503834,98.685652,96.73889,0.69714,0.05494,0.084669,40.14014,43.979058,39.232673,45.020747,205,30.693069,3.190319,0.227161,39.239239,1.260620e-02
WyFormer-harmonic-DiffCSP++,91.861648,0.173865,99.778516,82.613511,99.224806,95.843467,0.595018,0.096981,0.038729,35.096643,31.325301,35.862913,40.6639,228,32.519423,2.330744,0.173213,34.079349,1.593480e-01
WyForDiffCSP++,90.8,0.197137,99.669604,80.396476,99.229075,96.838382,0.626147,0.050064,0.084303,37.8,38.743455,37.577256,40.120968,211,30.718232,1.436464,0.216357,37.1,9.932239e-01
WyLLM-naive-DiffCSP++,94.892748,0.186222,99.677072,82.77718,98.493003,95.556047,0.47299,0.05991,0.016785,31.396534,28.49162,32.044888,36.734694,267,34.773218,1.295896,0.171783,30.682977,8.020991e-01
WyLLM-vanilla-DiffCSP++,96.126761,0.767399,99.6337,88.827839,94.505495,59.849657,2.235375,0.226658,0.258013,NaN,NaN,NaN,NaN,102,37.132353,2.022059,0.628919,NaN,3.934523e-01
WyLLM-site-symmetry-DiffCSP++,90.781563,0.229581,99.889625,83.88521,99.448124,96.440416,0.276627,NaN,0.040143,NaN,NaN,NaN,NaN,217,31.60221,2.209945,0.155485,NaN,2.154233e-01
CrystalFormer,80.465587,0.215094,87.421384,82.389937,99.874214,95.312845,0.403576,0.130221,0.14697,36.794355,28.571429,38.910013,39.2,103,24.604317,0.863309,0.28844,36.693548,2.976616e-01
DiffCSP++,90.590591,0.142541,100.0,85.082873,99.337017,95.909794,0.138519,0.042401,0.496008,42.3,46.052632,41.627358,47.67184,47,11.712707,2.541436,0.249526,41.7,9.045604e-02
DiffCSP,91.365462,0.218681,100.0,81.208791,99.56044,96.263542,0.785304,0.054588,0.290887,58.7,57.54717,59.010152,58.712121,93,16.043956,36.043956,7.710099,41.9,2.147836e-88
FlowMM,91.750503,0.182018,96.27193,82.565789,99.671053,96.650453,0.289166,0.047894,0.093082,51.15346,51.098901,51.165644,58.035714,64,10.022779,48.405467,13.406291,31.494483,3.199780e-139
MiAD,85.857573,0.198598,99.065421,84.228972,99.883178,94.240548,0.202986,0.05833,0.066253,NaN,NaN,NaN,NaN,68,11.556604,20.400943,4.755016,NaN,6.619743e-40
MatterGen,89.869609,0.207589,100.0,82.8125,99.776786,96.230378,0.309578,0.048118,0.226822,55.362615,58.767773,54.427083,55.743243,122,17.745536,24.776786,5.094787,43.820225,3.971041e-52
WyCryst,58.450704,0.247849,99.827883,76.7642,98.967298,89.818704,0.662624,0.172858,0.306926,41.448692,49.74359,39.42428,35.420744,193,43.103448,4.310345,0.629855,40.040241,5.884344e-04
train,100.0,0.201,100.0,89.9,99.9,96.683617,0.083239,0.038549,0.02861,NaN,NaN,NaN,NaN,0,0.0,1.5,0.143558,NaN,9.014792e-01

In [19]:
import numpy as np
def get_observation(name, column, n_structures=1000):
    all_observations = np.zeros(n_structures)
    all_observations[:int(table.at[name, column])] = 1.
    return all_observations

def compare_binary_columns(name1, name2, column):
    obs1 = get_observation(name1, column)
    obs2 = get_observation(name2, column)
    return ttest_ind(obs1, obs2)

for name in datasets:
    try:
        print(name, compare_binary_columns("WyForDiffCSP++", name, "Novel Uniques Templates (#)").pvalue)
    except ValueError:
        print(f"Failed to compare {name} with WyForDiffCSP++ for Novel Uniques Templates (#)")

Failed to compare WyckoffTransformer-raw with WyForDiffCSP++ for Novel Uniques Templates (#)
Failed to compare WyFormer-harmonic-raw with WyForDiffCSP++ for Novel Uniques Templates (#)
Failed to compare WyFormer-letters with WyForDiffCSP++ for Novel Uniques Templates (#)
WyFormer-letters-DiffCSP++ 0.48129218773786725
SymmCD 3.6355462366475895e-06
SymmCD-raw 1.2166969572031069e-07
WyFormer 0.7411343571033937
WyFormer-harmonic-DiffCSP++ 0.35866121902747644
WyForDiffCSP++ 1.0
WyLLM-naive-DiffCSP++ 0.003308618484875702
WyLLM-vanilla-DiffCSP++ 1.559253357677364e-11
WyLLM-site-symmetry-DiffCSP++ 0.7437222357931714
CrystalFormer 2.5414359012413026e-11
DiffCSP++ 1.22040077600833e-28
DiffCSP 1.4134765749800767e-13
FlowMM 4.899550987028511e-22
MiAD 1.1219443939694409e-20
MatterGen 8.415169829436187e-08
WyCryst 0.31634846285189944

In [20]:
symmetry_table = table.loc[["WyFormer-letters-DiffCSP++", "WyForDiffCSP++"],
                           ["Novel Uniques Templates (#)", "P1 (%)", "Space Group", "S.U.N. (%)", "S.S.U.N. (%)"]]

In [21]:
symmetry_table.style.format("{:.1f}").highlight_max(axis=0, props="font-weight: bold")

In [22]:
print(symmetry_table.to_markdown())

| Method                     |   Novel Uniques Templates (#) |   P1 (%) |   Space Group |   S.U.N. (%) |   S.S.U.N. (%) |
|:---------------------------|------------------------------:|---------:|--------------:|-------------:|---------------:|
| WyFormer-letters-DiffCSP++ |                           224 |  1.1655  |      0.219905 |      30.9698 |        30.4484 |
| WyForDiffCSP++             |                           211 |  1.43646 |      0.216357 |      37.8    |        37.1    |

In [23]:
symmetry_table_symmcd = table.loc[["SymmCD", "WyForDiffCSP++"],
                           ["Novel Uniques Templates (#)", "P1 (%)", "Space Group", "S.U.N. (%)", "S.S.U.N. (%)"]]

In [24]:
symmetry_table_symmcd.style.format("{:.2f}").highlight_max(axis=0, props="font-weight: bold")

In [25]:
print(symmetry_table_symmcd.to_markdown())

| Method         |   Novel Uniques Templates (#) |   P1 (%) |   Space Group |   S.U.N. (%) |   S.S.U.N. (%) |
|:---------------|------------------------------:|---------:|--------------:|-------------:|---------------:|
| SymmCD         |                           133 |  2.36686 |      0.240129 |         33.7 |           32.8 |
| WyForDiffCSP++ |                           211 |  1.43646 |      0.216357 |         37.8 |           37.1 |

In [26]:
table.loc[["WyFormer-letters-DiffCSP++", "WyForDiffCSP++"],
          ["Novelty (%)", "Structural", "Compositional", "Recall", "Precision", r"$\rho$", "$E$", "# Elements"]]

,Novelty (%),Structural,Compositional,Recall,Precision,$\rho$,$E$,# Elements
Method,,,,,,,,
WyFormer-letters-DiffCSP++,89.979123,99.535963,82.830626,98.143852,96.937873,0.432466,0.03743,0.114151
WyForDiffCSP++,90.8,99.669604,80.396476,99.229075,96.838382,0.626147,0.050064,0.084303

In [27]:
table.loc[:, ["S.U.N. (%)", "S.S.U.N. (%)"]]

                              S.U.N. (%) S.S.U.N. (%)
Method
WyckoffTransformer-raw               NaN          NaN
WyFormer-harmonic-raw                NaN          NaN
WyFormer-letters                     NaN          NaN
WyFormer-letters-DiffCSP++      30.96976    30.448384
SymmCD                              33.7         32.8
SymmCD-raw                           NaN          NaN
WyFormer                        40.14014    39.239239
WyFormer-harmonic-DiffCSP++    35.096643    34.079349
WyForDiffCSP++                      37.8         37.1
WyLLM-naive-DiffCSP++          31.396534    30.682977
WyLLM-vanilla-DiffCSP++              NaN          NaN
WyLLM-site-symmetry-DiffCSP++        NaN          NaN
CrystalFormer                  36.794355    36.693548
DiffCSP++                           42.3         41.7
DiffCSP                             58.7         41.9
FlowMM                          51.15346    31.494483
MiAD                                 NaN          NaN
MatterGen                      55.362615    43.820225
WyCryst                        41.448692    40.040241
train                                NaN          NaN

In [28]:
all_datasets[('split', 'test')].data.apply(record_to_anonymous_fingerprint, axis=1).isin(train_w_template_set).mean()

0.9713685606898077

In [29]:
max_subset=["Novelty (%)", "Structural", "Compositional", "Recall", "Precision", "S.S.U.N. (%)", "S.U.N. (%)", "Novel Template (%)"]
# -1 to exclude the MP-20 training set
def highlight_max_value(s):
    if s.name not in max_subset:
        return ['' for _ in s]
    is_max = s == s.max()
    #is_max.iloc[-1] = False
    return ['font-weight: bold' if v else '' for v in is_max]

min_subset=[r"$\rho$", "$E$", "# Elements", "# DoF", "Space Group", "Elements", "P1 (%)"]
def highlight_min_value(s):
    if s.name not in min_subset:
        return ['' for _ in s]
    is_min = s == s.min()
    #is_min.iloc[-1] = False
    return ['font-weight: bold' if v else '' for v in is_min]

In [31]:
def prettify(table):
    return table.style.format({
    "Novelty (%)": "{:.2f}",
    "Structural": "{:.2f}",
    "Compositional": "{:.2f}",
    "Recall": "{:.2f}",
    "Precision": "{:.2f}",
    r"$\rho$": "{:.2f}",
    "$E$": "{:.3f}",
    "# Elements": "{:.3f}",
    "# DoF": "{:.3f}",
    "Space Group": "{:.3f}",
    "Elements": "{:.3f}",
    "Novel Template (%)": "{:.2f}",
    "P1 (%)": "{:.2f}",
    "S.U.N. (%)": "{:.1f}",
    "S.S.U.N. (%)": "{:.1f}",
}).apply(highlight_max_value).apply(highlight_min_value)
prettify(table)

In [32]:
LLM_columns_1 = ["Novelty (%)", "Structural", "Compositional", "Recall", "Precision", r"$\rho$", "$E$", "# Elements"]
LLM_columns_2 = ["Novel Uniques Templates (#)", "P1 (%)", "Space Group"]

In [33]:
LLM_rows = ["WyForDiffCSP++", "WyLLM-naive-DiffCSP++", "WyLLM-vanilla-DiffCSP++", "WyLLM-site-symmetry-DiffCSP++"]

In [34]:
prettify(table.loc[["WyForDiffCSP++", "DiffCSP++", "DiffCSP", "FlowMM", "MiAD"], LLM_columns_1])

In [35]:
len(GeneratedDataset.from_cache(("WyckoffLLM-naive", )).data)

9492

In [36]:
len(GeneratedDataset.from_cache(("WyckoffLLM-site-symmetry", )).data)

7431

In [37]:
len(GeneratedDataset.from_cache(("WyckoffLLM-vanilla", )).data)

2866

In [41]:
raw_test_evaluator = StatisticalEvaluator(all_datasets[('split', 'test')].data)
cdvae_table = pd.DataFrame(index=pd.Index(datasets.keys(), tupleize_cols=False),
    columns=[
        "Structural", "Compositional",
        "Recall", "Precision",
        r"$\rho$", "$E$", "# Elements"])
sample_size_for_precision = 1000
for name, transformations in tqdm(datasets.items()):
    dataset = all_datasets[transformations]
    if "structure" in dataset.data.columns:
        cdvae_table.loc[name, "Compositional"] = 100*dataset.data.smact_validity.mean()
        cdvae_table.loc[name, "Structural"] = 100*dataset.data.structural_validity.mean()
        valid = dataset.data[dataset.data.naive_validity]
        cov_metrics = raw_test_evaluator.get_coverage(valid.cdvae_crystal)
        if len(valid) > sample_size_for_precision:
            valid_precision_sample = valid.sample(sample_size_for_precision, random_state=42, replace=False)        
            cov_metrics_subsampled = raw_test_evaluator.get_coverage(valid_precision_sample.cdvae_crystal)
            cdvae_table.loc[name, "Precision"] = 100*cov_metrics_subsampled["cov_precision"]
        else:
            cdvae_table.loc[name, "Precision"] = 100*cov_metrics["cov_precision"]
        cdvae_table.loc[name, "Recall"] = 100*cov_metrics["cov_recall"]
        cdvae_table.loc[name, r"$\rho$"] = raw_test_evaluator.get_density_emd(valid)
        cdvae_table.loc[name, "$E$"] = raw_test_evaluator.get_cdvae_e_emd(valid)
        cdvae_table.loc[name, "# Elements"] = raw_test_evaluator.get_num_elements_emd(valid)
prettify(cdvae_table)

  0%|          | 0/19 [00:00<?, ?it/s]

Ignoring 2 generated samples without composition fingerprints.

In [42]:
raw_test_evaluator = StatisticalEvaluator(all_datasets[('split', 'test')].data)
cdvae_table = pd.DataFrame(index=pd.Index(raw_datasets.keys(), tupleize_cols=False),
    columns=[
        "Structural", "Compositional",
        "Recall", "Precision",
        r"$\rho$", "$E$", "# Elements"])
sample_size_for_precision = 1000
for name, transformations in tqdm(list(raw_datasets.items())):
    dataset = all_datasets[transformations]
    if "structure" in dataset.data.columns:
        cdvae_table.loc[name, "Compositional"] = 100*dataset.data.smact_validity.mean()
        cdvae_table.loc[name, "Structural"] = 100*dataset.data.structural_validity.mean()
        valid = dataset.data[dataset.data.naive_validity]
        if len(valid) > sample_size_for_precision:
            valid_precision_sample = valid.sample(sample_size_for_precision, random_state=42, replace=False)        
            cov_metrics_subsampled = raw_test_evaluator.get_coverage(valid_precision_sample.cdvae_crystal)
            cdvae_table.loc[name, "Precision"] = 100*cov_metrics_subsampled["cov_precision"]
        else:
            cdvae_table.loc[name, "Precision"] = 100*cov_metrics["cov_precision"]
        cov_metrics = raw_test_evaluator.get_coverage(valid.cdvae_crystal)
        cdvae_table.loc[name, "Recall"] = 100*cov_metrics["cov_recall"]
        cdvae_table.loc[name, r"$\rho$"] = raw_test_evaluator.get_density_emd(valid)
        cdvae_table.loc[name, "$E$"] = raw_test_evaluator.get_cdvae_e_emd(valid)
        cdvae_table.loc[name, "# Elements"] = raw_test_evaluator.get_num_elements_emd(valid)
prettify(cdvae_table)

  0%|          | 0/12 [00:00<?, ?it/s]